# This file is part of «Letters of Russian sovereigns to the Republic of Venice» database.
#
# Copyright (c) Department of Linguistic and Literary Studies of the University of Padova
#
# «Letters of Russian sovereigns to the Republic of Venice» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Letters of Russian sovereigns to the Republic of Venice» database is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Letters of Russian sovereigns to the Republic of Venice» database,
# see <http://www.gnu.org/licenses/>.

security:
  enable_authenticator_manager: true
  password_hashers:
    App\Persistence\Entity\Security\User: auto
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
    ROLE_EDITOR: [ROLE_ADMIN]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_EDITOR, ROLE_ALLOWED_TO_SWITCH]
  providers:
    app_user_provider:
      entity:
        class: App\Persistence\Entity\Security\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      logout:
        path: security__logout
        target: security__login
      remember_me:
        secret: '%env(APP_SECRET)%'
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
  access_control:
    - { path: ^/admin/security.*, role: [ROLE_SUPER_ADMIN] }
    - { path: ^/admin/letter.*, role: [ROLE_EDITOR] }
    - { path: ^/admin/content.*, role: [ROLE_EDITOR] }
    - { path: ^/admin/bibliography.*, role: [ROLE_EDITOR] }
    - { path: ^/admin.*, role: [ROLE_ADMIN] }
    - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }